### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by fallenwitcher** [theothernt/AerialDream#10]
The app crashes randomly on Android TV 9. The screensaver starts and after pressing the back or home button the TV freezes and do a reboot.

**Comment by theothernt** [comment]
@fallenwitcher Can you give me a little bit more info about what you're running...

1. What is the name of the Android TV device?
2. Are you running 0.96 (the latest build)?
3. Did you run previous versions, did they have these issues?

This info will hopefully narrow down the issue and find a fix, Thanks!

**Comment by fallenwitcher** [comment]
Android 9 on TCL C715
Yes, this issue starts with the latest build. The previous build hasn't this random freeze.

**Comment by theothernt** [comment]
Thanks for replying. If you don't mind, can you uninstall 0.96 completely and install it again, then see if the issue persists?

**Comment by fallenwitcher** [comment]
Does not work. Same problem after reinstalling

**Comment by theothernt** [comment]
Ok, thanks for trying that. There are a couple of options...

1. Send me logs if possible
2. If not, I can make a new build with crash reporting built in

What suits?

**Comment by fallenwitcher** [comment]
An app with build in bug report is better for future problems.

**Comment by theothernt** [comment]
Ok, I'll add that feature in and have a new build tomorrow and let you know!

**Comment by theothernt** [comment]
@fallenwitcher I've added a new build with crash reporting if you'd like to try it...

https://github.com/theothernt/AerialDream/releases/tag/0.96-debug

It also contains a small fix for a crash that was happening on a couple of the Settings screens, which you may have experienced.

**Comment by fallenwitcher** [comment]
I will check it out

**Comment by fallenwitcher** [comment]
No random crashes so far. Maybe it's gone since your small fix but I will test a few days more.

**Comment by theothernt** [comment]
Glad to hear it, and thanks for testing the new build!

**Comment by fallenwitcher** [comment]
It looks like it has been fixed. Great work.
