### ISSUE TITLE
Support for auto update

### ISSUE THREAD

**Issue by prabjots07** [theothernt/AerialDream#11]
If possible, Can we get support for auto update?

**Comment by theothernt** [comment]
That's something I might look at in the future for these 'development' or 'preview' versions.

If there are no major issues with the version I've just posted (0.97), the plan is to get the app into the Play Store so more people can enjoy the app, plus the Play Store will auto-update the app for you.

**Comment by prabjots07** [comment]
SmarTube Next dev is using this to auto update app from github https://github.com/yuliskov/SharedModules/tree/master/appupdatechecker2. This would be helpful for development or preview version.

**Comment by theothernt** [comment]
Thanks, I had seen that as well - I currently have SmartTubeNext installed just to see the feature working over time, seems pretty good so far!

Much like STN, I'll probably need 2 versions - ie. two tracks - stable and beta.

**Comment by TtuxX** [comment]
Hey @theothernt :)
Sorry for reviving this issue, but an updater with changelog display like SmartTubeNext would be awesome ! It would allow for everyone to bypass Google + account requirement (less critical for AerialViews than STN - I agree)
