### ISSUE TITLE
Hdr not working on mi box 4k

### ISSUE THREAD

**Issue by Hotboy1987** [theothernt/AerialDream#12]
Plzz can you make hdr apple videos work on your program on mi box 4k ,, it keep give me black screen ,, but sdr apple videos work fine

**Comment by Hotboy1987** [comment]
something else ,, on sdr videos location not appear only file name ,, but on hdr videos even it's give me black screen on mi box s but it give me location name of the video

**Comment by Hotboy1987** [comment]
something to know ,, that I have 4k hdr tv(samsung q70a) and it has indicator to tell me if this video is hdr or not ,, and I can play hdr movies on my tv from mi box s

**Comment by theothernt** [comment]
Going on reports from various people with different makes of TV - it looks like your TV doesn't support Dolby Vision, only HDR10. As the videos come from Apple, they require Dolby Vision to play properly. Your Mi Box 4K is probably detecting the lack of DV support then not allowing the 4K HDR files to be played (these video files have no HDR10 info)

This is an issue I'm trying fix, and make the experience a better. For the moment, you'll have to stick to 4K SDR I'm afraid.

In relation to the other issue you mention about filenames and locations, are you playing *all* the files locally?

**Comment by Hotboy1987** [comment]
Thank you very much for your reply and your efforts ,, I will wait for
solution from you on next updates for hdr ,, and you are right ,, my tv are
hdr 10 support only ,, no dolby vision

And about location name and file name ,, yes I put all file locally on usb
,, and hdr videos black screen with location name ,, sdr works with no
problem but with file name not locations

**Comment by Hotboy1987** [comment]
plz can you tell me what is the different between this to videos 

LA_A006_C008_4K_SDR_HEVC

comp_LA_A006_C008_PSNK_ALL_LOGOS_v10_SDR_PS_FINAL_20180801_SDR_4K_HEVC

two videos is the same and I found it on google AppleTV Aerial Screen Saver Links ??

**Comment by theothernt** [comment]
The issue with the filenames happens because there are lists of videos for Apple's tvOS 11, 12 and 13 - my app only looks for the latest as I think they're the better versions, but some websites that list the videos use a mix so the filenames are different to what my app expects.

I will be creating my own website soon that lists all the Apple videos supported. In the meantime, the list I use is at... https://raw.githubusercontent.com/theothernt/AerialDream/master/app/src/main/res/raw/tvos13.json

In your example with the two videos, the 2nd filename is the latest tvOS 13 version - some videos have had their length, colours, etc adjusted.

**Comment by Hotboy1987** [comment]
you are right ,, when I use 

comp_LA_A006_C008_PSNK_ALL_LOGOS_v10_SDR_PS_FINAL_20180801_SDR_4K_HEVC

it gives me location name ,, but I have to choose sdr quality from setting ,, if I choose hdr quality from setting no location name just file name

**Comment by theothernt** [comment]
yes, each quality is a different file - 1080p SDR, 1080p HDR, 4k SDR, 4k HDR - so you have to pick the correct set, basically.

**Comment by theothernt** [comment]
I created a list of all the tvOS 13 videos... https://aerial-videos.netlify.app/

**Comment by Hotboy1987** [comment]
wow ,, very good step ,, but can you add location support for old videos like

DB_D001_C001_4K_SDR_HEVC
DB_D001_C005_4K_SDR_HEVC

because after watched old version and new one with re-coloring ,, I think old one is better and more natural color more than the new over coloring

**Comment by theothernt** [comment]
There isn't an easy way to add support for that, so the easiest thing to do if you find a video you prefer over the tvOS 13 version is to rename the file yourself...

DB_D001_C001_4K_SDR_HEVC -> Dubai
DB_D001_C005_4K_SDR_HEVC -> Dubai_

**Comment by Hotboy1987** [comment]
I know I can do this but I tell you to add location support to this video make your program more comprehensive for all apple Aerial Videos

**Comment by theothernt** [comment]
Ok, thanks for the suggestion - I'll add it to the list!

If you run into any more problems, please open feel free open a new issue :)

**Comment by Hotboy1987** [comment]
Thank you very much for all your efforts

**Comment by theothernt** [comment]
I appreciate that! ... and thanks for taking the time to report the initial issue and provide feedback. Lots of people use the app in different ways so it's useful to get these reports.
