### ISSUE TITLE
OLED Mode

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [theothernt/AerialDream#16]
Hey there. I love this awesome app!

I had a LG OLED TV now and I am bit paranoid about display-logo burning.

Is there a chance to move the text permantenlty and the clock? I use this app on my nvidia shield and disable thoose infos but they are nice.

**Comment by nirajsanghvi** [comment]
@sorryusernameisalreadytaken There's already a setting for this. In the Aerial Dream app on your shield, go to `Settings -> Interface` and select the third option down called "Alternate text position" which causes the title/location and time to switch sides every time the video changes.

**Comment by sorryusernameisalreadytaken** [comment]
Oh damn it. Sorry for this. :D

I love this app!

Thanks
