### ISSUE TITLE
Support for framerate match

### ISSUE THREAD

**Issue by prabjots07** [theothernt/AerialDream#17]
If possible can you please add framerate match?

**Comment by theothernt** [comment]
> If possible can you please add framerate match?

Can you give me an example of what you mean?

**Comment by prabjots07** [comment]
I recently upgraded my tv to OLED. For all other apps I'm using Shield's match frame rate feature to prevent judder. But that feature had to be manually triggered from settings each time.

I realized that some apps plex, kodi and SmartTube(for youtube) provides such feature inside the app. I am noob when it comes to programming, so forgive me if its not possible.

**Comment by Charlsburg** [comment]
Only time i've noticed FPS judder is if the Screensaver comes on while a video is paused in the background

**Comment by theothernt** [comment]
So I had look into 'frame rate match' for Nvidia Shield -  which works with 'adaptive frame rate' or 'variable refresh rate' which some newer TVs support.

The basic idea is that the device can inform the TV, monitor, etc what FPS the content is (24, 30, 60, 120 etc) so it can adapt its refresh rate to match giving a smoother appearance to *some* video.
