### ISSUE TITLE
Select which videos to play

### ISSUE THREAD

**Issue by jaqarll** [theothernt/AerialDream#19]
Hi there,
as my issue does not seem to get easily solved, I'd thought about explaining why I wanted to use smb in the first place: to select which videos are playing.

Is there any chance for an easy implementation of selecting which videos (either every single one as a selection or in groupings like China, Hong Kong, Los Angeles etc.) are played when the screen saver starts?

**Comment by theothernt** [comment]
It's a good idea but it will require some research on how it'll work best on a TV - lists + item selection is easy and fast on phone but quite clunky on a TV.

Having a short list of, say, locations and types of video (under water, space, in the air) might be better but it'll take time to categorise all that.
