### ISSUE TITLE
HDR Ocean Views Showing Up Green

### ISSUE THREAD

**Issue by razzamatazm** [theothernt/AerialDream#2]
Most of the HDR content seems to be working but the ocean looks to be green instead of blue. Maybe the HDR channel is not coming through correctly?

**Comment by razzamatazm** [comment]
This is on nvidia shield pro 2019. The app doesn’t appear to be triggering hdr/Dolby vision. If I run the app on my Sony Bravia x900h- the app works perfectly (and looks amazing)

**Comment by theothernt** [comment]
If you could, can you test the following for me...
* Set the video type to 1080p/HDR
* Set the video source to Remote (only)

**Comment by kristofferR** [comment]
Are you sure you've activated Dolby Vision on the Shield? It works great for me on my Shield Pro 2019 and LG C9.

It's under Settings - Device Preferences - Display & Sound. You should see the text "Dolby Vision and HDR10 Ready" in grey under Resolution and Dolby Vision should be toggled.

**Comment by razzamatazm** [comment]
The 0.93b is working great for me. I get a little popup that says the file type when the video switches, but it's fine.

Thanks!

**Comment by theothernt** [comment]
Thanks for the update, and I'm glad it's working for you.

That build you're using is a Debug build which has notifications turned on. The next release will have that turned off, so I'd recommend using that when it comes out.

**Comment by theothernt** [comment]
@razzamatazm new build added, please give it a try! https://github.com/theothernt/AerialDream/releases/tag/0.94-preview
