### ISSUE TITLE
Add features from the original version

### ISSUE THREAD

**Issue by Plazzmex** [theothernt/AerialDream#21]
Hi,

The latest original version introduced some new features.
Can you add them to your version?

1. Progress bar on the bottom of the screen
2. Bigger texts divided to clock on one side and name on the other side
3. Text that says "Loading Aerial..." In the middle of the screen when loading the video.

Thanks.

**Comment by theothernt** [comment]
I have a quick question for you @Plazzmex.

The 'Loading Aerial..." text was originally used to hide the pre-loading of 2 videos before play starts. My app doesn't use this method so should it should start a lot faster, or instantly. When the screensaver first starts, do you find there's a few seconds of black screen before you see a video playing?

**Comment by Plazzmex** [comment]
Yes, exactly

That's why I think it's more aesthetic to have the text, otherwise it's just black screen.

**Comment by theothernt** [comment]
Yeah, that makes sense. After the next major update is out (0.9 -> 1.0) I will be working more on the video playback part of the app.

**Comment by theothernt** [comment]
> Hi there :) I really miss the progress bar from Aerial Dream, will there be any integration of this in AerialViews? Thank you very much for your awesome app!

I'll see if I can add back the progress bar in the next few releases!

**Comment by theothernt** [comment]
It took a bit longer, but the progress bar should be in the next release.
