### ISSUE TITLE
Add custom files support

### ISSUE THREAD

**Issue by NewsGuyTor** [theothernt/AerialDream#5]
As far as I understand this app only supports local files with the same file names as the Apple playlist. 

I have 150 files I'd like to add (Complete Aerial Expansion Bundle), so I can't just replace the file names. Support for custom files that doesn't match the file names of the Apple playlist would be appreciated.

**Comment by theothernt** [comment]
Good idea - and I have to add that soon.

Basically, Android TV doesn't have any kind of file browser UI built in (the phone does), which would be a lot of work, so my current idea is to you either a) use the Apple playlist with remote or local files or b) play any files from a folder called /Videos - what do you think?

**Comment by NewsGuyTor** [comment]
I managed to bypass the issue by changing the json itself, removing the https stripper, and recompiling the app, which is frankly a better solution for me as I don't need to keep the files locally. However I think this would still be a good feature for other users.

I imagine that your suggestion would work great, however you should make it possible to store the files on external drives, the internal storage of most Android TV devices is tiny. The folder should also be called something other than just Videos (since I imagine many already have that folder for other uses). "Aerial Dream Videos" or something would be a good folder name.

**Comment by theothernt** [comment]
Glad you were able to get something working!

As for the local folder idea, I might go with something simple like /Aerial - but that folder can exist on any storage, local or external (the MediaStore API gives me a list of all videos regardless of storage location - Internal, USB, SD Card, etc)

**Comment by barrycraig** [comment]
Just chiming in to give support to this idea. The ability to simply populate a /Aerial folder with video files to include in the playlist would be fantastic. If there is anywhere to donate to this project let me know; a fully featured video screensaver app like this is somethingI think is worth proper investment.

**Comment by barrycraig** [comment]
> I managed to bypass the issue by changing the json itself, removing the https stripper, and recompiling the app, which is frankly a better solution for me as I don't need to keep the files locally. However I think this would still be a good feature for other users.
> 
> I imagine that your suggestion would work great, however you should make it possible to store the files on external drives, the internal storage of most Android TV devices is tiny. The folder should also be called something other than just Videos (since I imagine many already have that folder for other uses). "Aerial Dream Videos" or something would be a good folder name.

Would you be willing to share your json? I have the same expansion bundle and would like to include those files also.

**Comment by theothernt** [comment]
@barrycraig @NewsGuyTor I have a test version of the Aerial Dream with full local file support if you'd like to try it?

**Comment by barrycraig** [comment]
> @barrycraig @NewsGuyTor I have a test version of the Aerial Dream with full local file support if you'd like to try it?

I'd love to!

**Comment by theothernt** [comment]
The local playback of any video file has been added in the latest release, 0.96.
