### ISSUE TITLE
2015/17/18 movies

### ISSUE THREAD

**Issue by hackthis02** [theothernt/AerialDream#6]
This version works so much better on my Sony X900H. So thank you. 

My only question is there a reason you don't have the 2015/17/18 movies as well?

**Comment by theothernt** [comment]
Yes - each year does *not* contain a unique set of videos.

The 2019 manifest contains nearly all the previous videos, excepted they've tweaked the length, colour grading, etc. There are about 89 videos in total with about 5 removed (by Apple, not sure why).

In future, it will be possible to play any video you like - so if there was, for some reason, a particular version of a video from the 2015 manifest you liked, you could download and add that yourself.
