### ISSUE TITLE
Option to toggle location names while screensaver is running

### ISSUE THREAD

**Issue by barrycraig** [theothernt/AerialDream#7]
I much prefer the totally clean look of no clock or place names but sometimes when the screensaver is running in the background people in the room get curious about where the current video is located. It would be great to be able to hit a button on the remote and have the place name fade in.

**Comment by theothernt** [comment]
That's a good idea, I'll add it to the list. On Apple TV, you tap the remote (not press)... so I wonder if pressing the OK button or pressing UP would work... thoughts?

**Comment by barrycraig** [comment]
Funnily enough "Up" was my first thought as "OK" is quite an instinctual press to end the screensaver. I suppose the issue would be how you handle custom media (When it's supported), I guess it just doesn't have metadata support?

**Comment by theothernt** [comment]
Yeah, non-Apple videos would be an issue. The metadata for Apple's videos is not in the video itself, there's a separate list of text strings with time codes.

**Comment by theothernt** [comment]
Thinking a bit more about the issue with custom videos and their location names. One simple option is to use the filename without the extension, and apply proper casing. For example...

wicklow mountains.mp4 -> "Wicklow Mountains"
enniskerry-waterfall.mkv -> "Enniskerry Waterfall"

This would apply to a) local files and b) network shares only.

**Comment by duncanam** [comment]
Would like to +1 this feature for parity against the Apple Remote setup

**Comment by theothernt** [comment]
An update on this. In the next release you will be able to...

* Add gradients to the top or bottom of the screen
* Configure the overlays (ie. location, clock, etc) to appear initially, then disappear
* Configure any direction or OK button to reveal the overlays when press - with configurable timeout

There is a beta if you want to test the features, or the release should be out in the next week or so.
