### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by JimZiii** [theothernt/AerialDream#9]
I'm on a Nvidia Shield with the latest update (8.2.3) and it's crashing a bit much when changing settings.
Happens on a lot of random settings, especially the first time changing some settings and pretty consistently when selecting local source under videos and enabling local videos, like every second or third time changing them.
But like i said, it's also happening when changing other random settings, like some under interface.
It is possible to change these settings, i just have to start it back up after crashing and change it again, so it's more of an inconvenience than anything else.
It's only when changing settings so the streaming of videos itself and using the screensaver works fine.

**Comment by theothernt** [comment]
Thanks for reporting the issue @JimZiii, I have a couple of questions...

1. Is this issue with the latest version (0.96) ?
2. If it is, can you remove the app completely, install 0.96 again and see if the crashing persists?

**Comment by barrycraig** [comment]
Interestingly, I saw the same crash that @JimZiii is describing when selecting "local videos" on this build. I assumed I just needed a clean install it didn't happen again after that.

**Comment by JimZiii** [comment]
I had the original version before 0.96 so i didn't know it was a new bug.
Clearing the cash and data didn't solve it for me so i installed 0.95 which didn't have this bug, then upgraded back to 0.96 and the bug is gone. So a reinstall should solve it.
Thnx

**Comment by theothernt** [comment]
Thanks @barrycraig and @JimZiii for the info - hopefully a fresh install will work for you.

I'll close this issue but if any other crashes happen, please feel free to open a new issue.
